version: "3.7"
services:
  derby:
    image: opavlova/db-derby
    ports:
      - "1024:1527"
    volumes:
      - db-volume:/dbs/DOCKERDB
    restart: unless-stopped

  tomcat:
    image: com.webapp.gessi/gessi-slr:1.1.0
    depends_on:
      - derby
    ports:
      - "1025:8080"

networks:
  default:

volumes:
  db-volume:
    external: true